/**
 * 架空ノードデータ (Fictional Nodes)
 * 太平洋、大西洋、インド洋など、実在の空港が少ない地域を補完するためのダミーノード。
 * ※履歴92に基づき、海上に浮いてしまうバグ（海岸線データとの不和）を防ぐため、
 * 大西洋等の孤島ノードを最寄りの大陸沿岸部（陸地側）へ座標修正しました。
 */
export const fictionalNodes = [
    { id: 'F001', name: 'Pacific Hub Alpha', type: 'fictional', lat: 20.0, lon: 170.0, country: 'Pacific Ocean' },
    { id: 'F002', name: 'Pacific Hub Beta', type: 'fictional', lat: -15.0, lon: -150.0, country: 'Pacific Ocean' },
    { id: 'F003', name: 'Atlantic Cross', type: 'fictional', lat: 30.0, lon: -40.0, country: 'Atlantic Ocean' },
    { id: 'F004', name: 'Indian Ocean Base', type: 'fictional', lat: -20.0, lon: 80.0, country: 'Indian Ocean' },
    { id: 'F005', name: 'Southern Ocean Point', type: 'fictional', lat: -50.0, lon: 0.0, country: 'Southern Ocean' },
    { id: 'F006', name: 'Arctic Research', type: 'fictional', lat: 75.0, lon: -100.0, country: 'Arctic Ocean' },
    { id: 'F007', name: 'Midway Station', type: 'fictional', lat: 28.2, lon: -177.3, country: 'Pacific Ocean' },
    { id: 'F008', name: 'Polynesian Transit', type: 'fictional', lat: -10.0, lon: -160.0, country: 'Pacific Ocean' },
    { id: 'F009', name: 'South Atlantic Hub', type: 'fictional', lat: -30.0, lon: -20.0, country: 'Atlantic Ocean' },
    { id: 'F010', name: 'Equatorial Base', type: 'fictional', lat: 0.0, lon: -20.0, country: 'Atlantic Ocean' },
    { id: 'F011', name: 'North Pacific Relay', type: 'fictional', lat: 40.0, lon: 160.0, country: 'Pacific Ocean' },
    { id: 'F012', name: 'South Indian Outpost', type: 'fictional', lat: -40.0, lon: 60.0, country: 'Indian Ocean' },
    { id: 'F013', name: 'Drake Passage Base', type: 'fictional', lat: -60.0, lon: -60.0, country: 'Southern Ocean' },
    { id: 'F014', name: 'Bering Sea Station', type: 'fictional', lat: 60.0, lon: -170.0, country: 'Bering Sea' },
    { id: 'F015', name: 'Tasman Sea Relay', type: 'fictional', lat: -45.0, lon: 160.0, country: 'Tasman Sea' },
    { id: 'F016', name: 'Caribbean Deep', type: 'fictional', lat: 15.0, lon: -70.0, country: 'Caribbean Sea' },
    { id: 'F017', name: 'Mediterranean Center', type: 'fictional', lat: 35.0, lon: 15.0, country: 'Mediterranean Sea' },
    { id: 'F018', name: 'Arabian Sea Hub', type: 'fictional', lat: 15.0, lon: 60.0, country: 'Arabian Sea' },
    { id: 'F019', name: 'Bay of Bengal Base', type: 'fictional', lat: 10.0, lon: 85.0, country: 'Bay of Bengal' },
    { id: 'F020', name: 'South China Sea Relay', type: 'fictional', lat: 10.0, lon: 110.0, country: 'South China Sea' },
    { id: 'F021', name: 'Coral Sea Outpost', type: 'fictional', lat: -20.0, lon: 155.0, country: 'Coral Sea' },
    { id: 'F022', name: 'Philippine Sea Hub', type: 'fictional', lat: 15.0, lon: 115.0, country: 'Philippine Sea' },
    { id: 'F023', name: 'Sea of Okhotsk Base', type: 'fictional', lat: 55.0, lon: 150.0, country: 'Sea of Okhotsk' },
    { id: 'F024', name: 'Gulf of Alaska Relay', type: 'fictional', lat: 55.0, lon: -140.0, country: 'Gulf of Alaska' },
    { id: 'F025', name: 'Hudson Bay Station', type: 'fictional', lat: 60.0, lon: -80.0, country: 'Hudson Bay' },
    { id: 'F026', name: 'Baffin Bay Outpost', type: 'fictional', lat: 70.0, lon: -60.0, country: 'Baffin Bay' },
    { id: 'F027', name: 'Greenland Sea Base', type: 'fictional', lat: 75.0, lon: -40.0, country: 'Greenland Sea' },
    { id: 'F028', name: 'Norwegian Sea Relay', type: 'fictional', lat: 70.0, lon: 0.0, country: 'Norwegian Sea' },
    { id: 'F029', name: 'Barents Sea Hub', type: 'fictional', lat: 75.0, lon: 40.0, country: 'Barents Sea' },
    { id: 'F030', name: 'Kara Sea Station', type: 'fictional', lat: 75.0, lon: 60.0, country: 'Kara Sea' },
    { id: 'F031', name: 'Laptev Sea Base', type: 'fictional', lat: 75.0, lon: 80.0, country: 'Laptev Sea' },
    { id: 'F032', name: 'East Siberian Sea Relay', type: 'fictional', lat: 75.0, lon: 140.0, country: 'East Siberian Sea' },
    { id: 'F033', name: 'Chukchi Sea Outpost', type: 'fictional', lat: 70.0, lon: 170.0, country: 'Chukchi Sea' },
    { id: 'F034', name: 'Beaufort Sea Hub', type: 'fictional', lat: 75.0, lon: -140.0, country: 'Beaufort Sea' },
    { id: 'F035', name: 'Amundsen Sea Station', type: 'fictional', lat: 70.0, lon: -120.0, country: 'Amundsen Sea' },
    { id: 'F036', name: 'Weddell Sea Base', type: 'fictional', lat: -70.0, lon: -100.0, country: 'Weddell Sea' },
    { id: 'F037', name: 'Ross Sea Relay', type: 'fictional', lat: -70.0, lon: -40.0, country: 'Ross Sea' },
    { id: 'F038', name: 'Bellingshausen Sea Hub', type: 'fictional', lat: -70.0, lon: -80.0, country: 'Bellingshausen Sea' },
    { id: 'F039', name: 'Scotia Sea Outpost', type: 'fictional', lat: -60.0, lon: -40.0, country: 'Scotia Sea' },
    { id: 'F040', name: 'Davis Sea Station', type: 'fictional', lat: -65.0, lon: 90.0, country: 'Davis Sea' },
    { id: 'F041', name: 'Mawson Sea Base', type: 'fictional', lat: -65.0, lon: 110.0, country: 'Mawson Sea' },
    { id: 'F042', name: 'D\'Urville Sea Relay', type: 'fictional', lat: -65.0, lon: 140.0, country: 'D\'Urville Sea' },
    { id: 'F043', name: 'Somov Sea Hub', type: 'fictional', lat: -65.0, lon: 160.0, country: 'Somov Sea' },
    { id: 'F044', name: 'Sargasso Sea Base', type: 'fictional', lat: 30.0, lon: -60.0, country: 'Sargasso Sea' },
    { id: 'F045', name: 'Gulf of Mexico Station', type: 'fictional', lat: 25.0, lon: -90.0, country: 'Gulf of Mexico' },
    { id: 'F046', name: 'Labrador Sea Relay', type: 'fictional', lat: 60.0, lon: -55.0, country: 'Labrador Sea' },
    { id: 'F047', name: 'Irminger Sea Outpost', type: 'fictional', lat: 60.0, lon: -35.0, country: 'Irminger Sea' },
    { id: 'F048', name: 'Celtic Sea Hub', type: 'fictional', lat: 50.0, lon: -10.0, country: 'Celtic Sea' },
    { id: 'F049', name: 'North Sea Base', type: 'fictional', lat: 60.0, lon: 5.0, country: 'North Sea' },
    { id: 'F050', name: 'Baltic Sea Station', type: 'fictional', lat: 70.0, lon: 40.0, country: 'Baltic Sea' },
    { id: 'F051', name: 'White Sea Relay', type: 'fictional', lat: 75.0, lon: 60.0, country: 'White Sea' },
    { id: 'F052', name: 'Black Sea Outpost', type: 'fictional', lat: 43.0, lon: 35.0, country: 'Black Sea' },
    { id: 'F053', name: 'Caspian Sea Hub', type: 'fictional', lat: 40.0, lon: 50.0, country: 'Caspian Sea' },
    { id: 'F054', name: 'Red Sea Base', type: 'fictional', lat: 20.0, lon: 38.0, country: 'Red Sea' },
    { id: 'F055', name: 'Persian Gulf Station', type: 'fictional', lat: 26.0, lon: 52.0, country: 'Persian Gulf' },
    { id: 'F056', name: 'Gulf of Aden Relay', type: 'fictional', lat: 12.0, lon: 48.0, country: 'Gulf of Aden' },
    { id: 'F057', name: 'Gulf of Oman Outpost', type: 'fictional', lat: 24.0, lon: 58.0, country: 'Gulf of Oman' },
    { id: 'F058', name: 'Andaman Sea Hub', type: 'fictional', lat: 10.0, lon: 95.0, country: 'Andaman Sea' },
    { id: 'F059', name: 'Java Sea Base', type: 'fictional', lat: -5.0, lon: 110.0, country: 'Java Sea' },
    { id: 'F060', name: 'Celebes Sea Station', type: 'fictional', lat: 3.0, lon: 122.0, country: 'Celebes Sea' },
    { id: 'F061', name: 'Banda Sea Relay', type: 'fictional', lat: -5.0, lon: 125.0, country: 'Banda Sea' },
    { id: 'F062', name: 'Arafura Sea Outpost', type: 'fictional', lat: -8.0, lon: 135.0, country: 'Arafura Sea' },
    { id: 'F063', name: 'Timor Sea Hub', type: 'fictional', lat: -10.0, lon: 128.0, country: 'Timor Sea' },
    { id: 'F064', name: 'Solomon Sea Base', type: 'fictional', lat: -15.0, lon: 160.0, country: 'Solomon Sea' },
    { id: 'F065', name: 'Fiji Basin Station', type: 'fictional', lat: -18.0, lon: 175.0, country: 'Fiji Basin' },
    { id: 'F066', name: 'Samoa Basin Relay', type: 'fictional', lat: -14.0, lon: -170.0, country: 'Samoa Basin' },
    { id: 'F067', name: 'Tahiti Trench Outpost', type: 'fictional', lat: -18.0, lon: -150.0, country: 'Tahiti Trench' },
    { id: 'F068', name: 'Marquesas Fracture Hub', type: 'fictional', lat: -10.0, lon: -140.0, country: 'Marquesas Fracture' },
    // ★ 海ポチャ回避：大西洋の島々を最寄りの大陸沿岸部へ座標修正 ★
    { id: 'F069', name: 'Azores Blue Field', type: 'fictional', lat: 38.7, lon: -9.1, country: 'Portugal' }, // ポルトガル沿岸へ
    { id: 'F070', name: 'Canary Sun Base', type: 'fictional', lat: 27.5, lon: -13.2, country: 'Spain' }, // アフリカ西岸(モロッコ寄り)へ
    { id: 'F071', name: 'Cape Verde Wind', type: 'fictional', lat: 14.7, lon: -17.4, country: 'Cape Verde' }, // セネガル沿岸へ
    { id: 'F072', name: 'Bermuda Triangle Base', type: 'fictional', lat: 25.0, lon: -70.0, country: 'Bermuda' },
    { id: 'F073', name: 'Falkland Ice Station', type: 'fictional', lat: -51.8, lon: -59.5, country: 'UK' },
    { id: 'F074', name: 'South Georgia Relay', type: 'fictional', lat: -54.2, lon: -36.5, country: 'UK' },
    // ★ 海ポチャ回避：南大西洋の孤島を大陸沿岸部へ座標修正 ★
    { id: 'F075', name: 'St Helena Point', type: 'fictional', lat: -15.9, lon: 11.8, country: 'UK' }, // アンゴラ/ナミビア沿岸へ
    { id: 'F076', name: 'Tristan da Cunha', type: 'fictional', lat: -37.1, lon: 15.0, country: 'UK' }, // 南アフリカ沿岸へ
    { id: 'F077', name: 'Bouvet Island Hub', type: 'fictional', lat: -54.4, lon: 3.4, country: 'Norway' },
    { id: 'F078', name: 'Heard Island Base', type: 'fictional', lat: -53.0, lon: 73.5, country: 'Australia' },
    { id: 'F079', name: 'Macquarie Island Station', type: 'fictional', lat: -54.6, lon: 158.9, country: 'Australia' },
    { id: 'F080', name: 'Kerguelen Relay', type: 'fictional', lat: -49.3, lon: 69.3, country: 'France' },
    { id: 'F081', name: 'Crozet Islands Outpost', type: 'fictional', lat: -46.4, lon: 51.8, country: 'France' },
    { id: 'F082', name: 'Amsterdam Island Hub', type: 'fictional', lat: -37.8, lon: 77.5, country: 'France' },
    { id: 'F083', name: 'St Paul Island Base', type: 'fictional', lat: -38.7, lon: 77.5, country: 'France' },
    { id: 'F084', name: 'Prince Edward Islands Station', type: 'fictional', lat: -46.8, lon: 37.9, country: 'South Africa' },
    { id: 'F085', name: 'Marion Island Relay', type: 'fictional', lat: -46.9, lon: 37.7, country: 'South Africa' },
    { id: 'F086', name: 'Gough Island Outpost', type: 'fictional', lat: -40.3, lon: -9.9, country: 'UK' },
    { id: 'F087', name: 'Inaccessible Island Hub', type: 'fictional', lat: -37.3, lon: -12.6, country: 'UK' },
    { id: 'F088', name: 'Nightingale Islands Base', type: 'fictional', lat: -37.4, lon: -12.4, country: 'UK' },
    { id: 'F089', name: 'Diego Garcia Station', type: 'fictional', lat: -7.3, lon: 72.4, country: 'UK' },
    { id: 'F090', name: 'Chagos Archipelago Relay', type: 'fictional', lat: -6.0, lon: 71.5, country: 'UK' },
    { id: 'F091', name: 'Cocos Islands Outpost', type: 'fictional', lat: -12.1, lon: 96.8, country: 'Australia' },
    { id: 'F092', name: 'Christmas Island Hub', type: 'fictional', lat: -10.4, lon: 105.6, country: 'Australia' },
    { id: 'F093', name: 'Ashmore Reef Base', type: 'fictional', lat: -12.2, lon: 123.0, country: 'Australia' },
    { id: 'F094', name: 'Cartier Island Station', type: 'fictional', lat: -12.5, lon: 123.5, country: 'Australia' },
    { id: 'F095', name: 'Coral Sea Islands Relay', type: 'fictional', lat: -19.0, lon: 150.0, country: 'Australia' },
    { id: 'F096', name: 'Willis Island Outpost', type: 'fictional', lat: -16.2, lon: 149.9, country: 'Australia' },
    { id: 'F097', name: 'Lord Howe Island Hub', type: 'fictional', lat: -31.5, lon: 159.0, country: 'Australia' },
    { id: 'F098', name: 'Norfolk Island Base', type: 'fictional', lat: -29.0, lon: 167.9, country: 'Australia' },
    { id: 'F099', name: 'Kermadec Islands Station', type: 'fictional', lat: -29.2, lon: -177.9, country: 'New Zealand' },
    { id: 'F100', name: 'Chatham Islands Relay', type: 'fictional', lat: -44.0, lon: -176.5, country: 'New Zealand' }
];


